jobs:
  include:
    - stage : build wasm worker
  # Builds with wasm-pack.
      rust: beta
      env: RUST_BACKTRACE=1
      before_script:
        - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
        - (test -x $HOME/.cargo/bin/cargo-generate || cargo install --vers "^0.2" cargo-generate)
        - cargo install-update -a
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
      scrip:
        - sh ./build.sh
    - stage : build Vue.js App
      langage : node_js
      before_script:
        - cd ../edf-viewer-app
        - npm install
      script:
        - npm run build