jobs:
  include:
    - stage : build wasm worker
  # Builds with wasm-pack.
      language: node_js
      node_js:
        - "10"
      cache: cargo
      before_install:
        - node --version
        - curl https://sh.rustup.rs -sSf | sh -s -- -y # install rust
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh # install wasm-pack
      install:

        # - rustup target add wasm32-unknown-unknown
        # - (test -x $HOME/.cargo/bin/wasm-pack || cargo install wasm-pack)
        - cd ../edf-viewer-app
        - npm install
        - cd ../
      script:
        - cd edf-viewer-worker && sh ./build.sh
        - cd ..
        - cd edf-viewer-app && npm run build