matrix:
  include:
    - language: rust
      before_script:
        - cd edf-viewer-worker
      script:
        - sh ./build.sh
    - langage : npm
      before_script:
        - npm install
      script:
        - npm run build