/** Declaration file generated by dts-gen */

export function CalcCascades(): any;

export function Fft(r: any): any;

export function FirCoeffs(): any;

export function FirFilter(r: any): any;

export function IirCoeffs(): any;

export function IirFilter(r: any): any;

export function TestFilter(r: any): any;

export namespace CalcCascades {
    const prototype: {
    };

}

export namespace Fft {
    const prototype: {
    };

}

export namespace FirCoeffs {
    const prototype: {
    };

}

export namespace FirFilter {
    const prototype: {
    };

}

export namespace IirCoeffs {
    const prototype: {
    };

}

export namespace IirFilter {
    const prototype: {
    };

}

export namespace TestFilter {
    const prototype: {
    };

}

